# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQyEtBo9x2J1oXy6LnYZnhCjkYFiF9OT
"""

from health_agent import HealthAgent
from safety_agent import SafetyAgent
from reminder_agent import ReminderAgent

class CoordinatorAgent:
    def __init__(self):
        self.health_agent = HealthAgent()
        self.safety_agent = SafetyAgent()
        self.reminder_agent = ReminderAgent()

    def run(self, health_df, safety_df, reminder_df):
        print("Running Health Monitoring Agent...")
        self.health_agent.process(health_df)

        print("\nRunning Safety Monitoring Agent...")
        self.safety_agent.process(safety_df)

        print("\nRunning Reminder Agent...")
        self.reminder_agent.process(reminder_df)