# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQyEtBo9x2J1oXy6LnYZnhCjkYFiF9OT
"""

from coordinator import CoordinatorAgent
import pandas as pd

# Load datasets
health_data = pd.read_csv("data/health_monitoring.csv")
safety_data = pd.read_csv("data/safety_monitoring.csv")
reminder_data = pd.read_csv("data/daily_reminder.csv")

# Initialize Coordinator Agent
coordinator = CoordinatorAgent()
coordinator.run(health_data, safety_data, reminder_data)