# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQyEtBo9x2J1oXy6LnYZnhCjkYFiF9OT
"""

from utils import alert

class SafetyAgent:
    def __init__(self):
        pass

    def process(self, df):
        for _, row in df.iterrows():
            if row['FallDetected'] == 1:
                alert("Fall Detected", row)
            if row['InactivityMinutes'] > 60:
                alert("Prolonged Inactivity", row)