# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQyEtBo9x2J1oXy6LnYZnhCjkYFiF9OT
"""

def alert(message, data_row):
    print(f"[ALERT] {message} for {data_row['Name']} at {data_row['Timestamp']}")